name: Build for Mac

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:

  build-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install python2.7
        run: |
          brew install pyenv
          pyenv install 2.7.18
          pyenv global 2.7.18

      - name: Npm Install
        run: |
          pip install setuptools
          npm ci

      - name: Build Dist
        env:
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: |
          export PYTHON_PATH=$(pyenv root)/shims/python
          npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenBlock-Desktop-darwin
          path: dist/OpenBlock-Desktop*.dmg
          retention-days: 1
